name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build-linux:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        git clone https://github.com/vial-kb/vial-gui.git
        git clone https://github.com/vial-kb/via-keymap-precompiled.git
        ./fetch-emsdk.sh
        ./fetch-deps.sh
        ./build-deps.sh
        cd src
        ./build.sh

    - uses: actions/upload-artifact@v4
      with:
        name: vial-web
        path: src/build
